<?php
//CMS cache file, DO NOT modify me!
//Created on February 7, 2017, 17:58

$NodeInfo = array (
  'NodeID' => '86',
  'NodeGUID' => '91yxq.cqby2.server',
  'TableID' => '6',
  'ParentID' => '85',
  'RootID' => '0',
  'InheritNodeID' => '0',
  'NodeType' => '1',
  'NodeSort' => '0',
  'Name' => '开服列表',
  'ContentPSN' => '{PSN:6}/list',
  'ContentURL' => '{PSN-URL:6}/list',
  'ResourcePSN' => '{PSN:6}/rsc/games/cqby2',
  'ResourceURL' => '{PSN-URL:6}/rsc/games/cqby2',
  'PublishMode' => '1',
  'IndexTpl' => '/www/games/cqby2/server_list.html',
  'IndexName' => 'index.html',
  'ContentTpl' => '/www/games/cqby2/server_list.html',
  'ImageTpl' => '',
  'SubDir' => '',
  'PublishFileFormat' => 'index.html',
  'IsComment' => '0',
  'CommentLength' => NULL,
  'IsPrint' => '0',
  'IsGrade' => '0',
  'IsMail' => '0',
  'Disabled' => '0',
  'AutoPublish' => '2',
  'IndexPortalURL' => 'http://91yxq.com/publish/index.php/{NodeID},{Page}.html',
  'ContentPortalURL' => 'http://91yxq.com/publish/content.php/{IndexID},{Page}.html',
  'Pager' => '#default.php',
  'Editor' => 'default.php',
  'WorkFlow' => '0',
  'PermissionManageG' => '',
  'PermissionManageU' => '',
  'PermissionReadG' => '',
  'PermissionReadU' => '',
  'PermissionWriteG' => '',
  'PermissionWriteU' => '',
  'PermissionApproveG' => '',
  'PermissionApproveU' => '',
  'PermissionPublishG' => '',
  'PermissionPublishU' => '',
  'PermissionInherit' => '0',
  'show' => '1',
  'CreationUserID' => '1',
  'SubNodeID' => '86',
  'ParentNodeID' => '1%3%85%86',
  'Nav' => 'a:4:{i:0;a:2:{s:6:"NodeID";s:1:"1";s:4:"Name";s:13:"91yxq游戏";}i:1;a:2:{s:6:"NodeID";s:1:"3";s:4:"Name";s:19:"91yxq游戏官网";}i:2;a:2:{s:6:"NodeID";s:2:"85";s:4:"Name";s:16:"传奇霸业test";}i:3;a:2:{s:6:"NodeID";s:2:"86";s:4:"Name";s:12:"开服列表";}}',
  'URL' => 'http://www.91yxq.com/cqby2/list/index.html',
  'Navigation' => 
  array (
    0 => 
    array (
      'NodeID' => '1',
      'Name' => '91yxq游戏',
      'URL' => '/index.html',
      'NodeName' => '91yxq游戏',
      'NodeURL' => '/index.html',
    ),
    1 => 
    array (
      'NodeID' => '3',
      'Name' => '91yxq游戏官网',
      'URL' => NULL,
      'NodeName' => '91yxq游戏官网',
      'NodeURL' => NULL,
    ),
    2 => 
    array (
      'NodeID' => '85',
      'Name' => '传奇霸业test',
      'URL' => 'http://www.91yxq.com/cqby2/index.html',
      'NodeName' => '传奇霸业test',
      'NodeURL' => 'http://www.91yxq.com/cqby2/index.html',
    ),
    3 => 
    array (
      'NodeID' => '86',
      'Name' => '开服列表',
      'URL' => 'http://www.91yxq.com/cqby2/list/index.html',
      'NodeName' => '开服列表',
      'NodeURL' => 'http://www.91yxq.com/cqby2/list/index.html',
    ),
  ),
);
?>