<?php
//CMS cache file, DO NOT modify me!
//Created on December 29, 2016, 20:41

$NodeInfo = array (
  'NodeID' => '16',
  'NodeGUID' => '91yxq.www.help.pay',
  'TableID' => '1',
  'ParentID' => '9',
  'RootID' => '0',
  'InheritNodeID' => '0',
  'NodeType' => '1',
  'NodeSort' => '0',
  'Name' => '充值问题',
  'ContentPSN' => '{PSN:1}/help',
  'ContentURL' => '{PSN-URL:1}/help',
  'ResourcePSN' => '{PSN:2}/rsc/www/servicecenter',
  'ResourceURL' => '{PSN-URL:2}/rsc/www/servicecenter',
  'PublishMode' => '1',
  'IndexTpl' => '/www/help/help_list.html',
  'IndexName' => 'pay.html',
  'ContentTpl' => '/www/help/help_detail.html',
  'ImageTpl' => '',
  'SubDir' => 'Y/md',
  'PublishFileFormat' => '{ContentID}.html',
  'IsComment' => '0',
  'CommentLength' => NULL,
  'IsPrint' => '0',
  'IsGrade' => '0',
  'IsMail' => '0',
  'Disabled' => '0',
  'AutoPublish' => '2',
  'IndexPortalURL' => 'http://manage.test.com/publish/index.php/{NodeID},{Page}.html',
  'ContentPortalURL' => 'http://manage.test.com/publish/content.php/{IndexID},{Page}.html',
  'Pager' => '#default.php',
  'Editor' => 'default.php',
  'WorkFlow' => '0',
  'PermissionManageG' => '',
  'PermissionManageU' => '',
  'PermissionReadG' => '',
  'PermissionReadU' => '',
  'PermissionWriteG' => '',
  'PermissionWriteU' => '',
  'PermissionApproveG' => '',
  'PermissionApproveU' => '',
  'PermissionPublishG' => '',
  'PermissionPublishU' => '',
  'PermissionInherit' => '0',
  'show' => '1',
  'CreationUserID' => '1',
  'SubNodeID' => '16',
  'ParentNodeID' => '1%2%9%16',
  'Nav' => 'a:4:{i:0;a:2:{s:6:"NodeID";s:1:"1";s:4:"Name";s:13:"91yxq游戏";}i:1;a:2:{s:6:"NodeID";s:1:"2";s:4:"Name";s:13:"91yxq平台";}i:2;a:2:{s:6:"NodeID";s:1:"9";s:4:"Name";s:12:"客服中心";}i:3;a:2:{s:6:"NodeID";s:2:"16";s:4:"Name";s:12:"充值问题";}}',
  'URL' => 'http://www.91yxq.com/help/pay.html',
  'Navigation' => 
  array (
    0 => 
    array (
      'NodeID' => '1',
      'Name' => '91yxq游戏',
      'URL' => '/index.html',
      'NodeName' => '91yxq游戏',
      'NodeURL' => '/index.html',
    ),
    1 => 
    array (
      'NodeID' => '2',
      'Name' => '91yxq平台',
      'URL' => 'http://www.91yxq.com/index.html',
      'NodeName' => '91yxq平台',
      'NodeURL' => 'http://www.91yxq.com/index.html',
    ),
    2 => 
    array (
      'NodeID' => '9',
      'Name' => '客服中心',
      'URL' => 'http://www.91yxq.com/help/index.html',
      'NodeName' => '客服中心',
      'NodeURL' => 'http://www.91yxq.com/help/index.html',
    ),
    3 => 
    array (
      'NodeID' => '16',
      'Name' => '充值问题',
      'URL' => 'http://www.91yxq.com/help/pay.html',
      'NodeName' => '充值问题',
      'NodeURL' => 'http://www.91yxq.com/help/pay.html',
    ),
  ),
);
?>