<?php
//CMS cache file, DO NOT modify me!
//Created on March 31, 2017, 16:57

$NodeInfo = array (
  'NodeID' => '102',
  'NodeGUID' => '91yxq.msb.yxjt',
  'TableID' => '1',
  'ParentID' => '89',
  'RootID' => '0',
  'InheritNodeID' => '0',
  'NodeType' => '1',
  'NodeSort' => '0',
  'Name' => '游戏截图',
  'ContentPSN' => '{PSN:9}/yxjt',
  'ContentURL' => '{PSN-URL:9}/yxjt',
  'ResourcePSN' => '{PSN:9}/rsc/games/hys/yxjt',
  'ResourceURL' => '{PSN-URL:9}/rsc/games/hys/yxjt',
  'PublishMode' => '1',
  'IndexTpl' => '/www/games/hys/news_list.html',
  'IndexName' => 'index.html',
  'ContentTpl' => '/www/games/hys/detail.html',
  'ImageTpl' => '',
  'SubDir' => '',
  'PublishFileFormat' => '{ContentID}.html',
  'IsComment' => '0',
  'CommentLength' => NULL,
  'IsPrint' => '0',
  'IsGrade' => '0',
  'IsMail' => '0',
  'Disabled' => '0',
  'AutoPublish' => '2',
  'IndexPortalURL' => 'http://91yxq.com/publish/index.php/{NodeID},{Page}.html',
  'ContentPortalURL' => 'http://91yxq.com/publish/content.php/{IndexID},{Page}.html',
  'Pager' => '#default.php',
  'Editor' => 'default.php',
  'WorkFlow' => '0',
  'PermissionManageG' => '',
  'PermissionManageU' => '',
  'PermissionReadG' => '',
  'PermissionReadU' => '',
  'PermissionWriteG' => '',
  'PermissionWriteU' => '',
  'PermissionApproveG' => '',
  'PermissionApproveU' => '',
  'PermissionPublishG' => '',
  'PermissionPublishU' => '',
  'PermissionInherit' => '0',
  'show' => '1',
  'CreationUserID' => '1',
  'SubNodeID' => '102',
  'ParentNodeID' => '1%3%89%102',
  'Nav' => 'a:4:{i:0;a:2:{s:6:"NodeID";s:1:"1";s:4:"Name";s:11:"91yxq游戏";}i:1;a:2:{s:6:"NodeID";s:1:"3";s:4:"Name";s:17:"91yxq游戏官网";}i:2;a:2:{s:6:"NodeID";s:2:"89";s:4:"Name";s:9:"火焰神";}i:3;a:2:{s:6:"NodeID";s:3:"102";s:4:"Name";s:12:"游戏截图";}}',
  'URL' => 'http://www.demo.com/hys/yxjt/index.html',
  'Navigation' => 
  array (
    0 => 
    array (
      'NodeID' => '1',
      'Name' => '91yxq游戏',
      'URL' => '/index.html',
      'NodeName' => '91yxq游戏',
      'NodeURL' => '/index.html',
    ),
    1 => 
    array (
      'NodeID' => '3',
      'Name' => '91yxq游戏官网',
      'URL' => NULL,
      'NodeName' => '91yxq游戏官网',
      'NodeURL' => NULL,
    ),
    2 => 
    array (
      'NodeID' => '89',
      'Name' => '火焰神',
      'URL' => 'http://www.demo.com/hys/index.html',
      'NodeName' => '火焰神',
      'NodeURL' => 'http://www.demo.com/hys/index.html',
    ),
    3 => 
    array (
      'NodeID' => '102',
      'Name' => '游戏截图',
      'URL' => 'http://www.demo.com/hys/yxjt/index.html',
      'NodeName' => '游戏截图',
      'NodeURL' => 'http://www.demo.com/hys/yxjt/index.html',
    ),
  ),
);
?>