<?php
//CMS cache file, DO NOT modify me!
//Created on March 31, 2017, 16:56

$NodeInfo = array (
  'NodeID' => '3',
  'NodeGUID' => '91yxq.gameweb',
  'TableID' => '1',
  'ParentID' => '1',
  'RootID' => '0',
  'InheritNodeID' => '0',
  'NodeType' => '1',
  'NodeSort' => '0',
  'Name' => '91yxq游戏官网',
  'ContentPSN' => '',
  'ContentURL' => '',
  'ResourcePSN' => '',
  'ResourceURL' => '',
  'PublishMode' => '0',
  'IndexTpl' => '',
  'IndexName' => 'index.html',
  'ContentTpl' => '',
  'ImageTpl' => '',
  'SubDir' => 'Y-m-d',
  'PublishFileFormat' => '{TimeStamp}d{ContentID}.html',
  'IsComment' => '0',
  'CommentLength' => NULL,
  'IsPrint' => '0',
  'IsGrade' => '0',
  'IsMail' => '0',
  'Disabled' => '0',
  'AutoPublish' => '2',
  'IndexPortalURL' => 'http://manage.test.com/publish/index.php/{NodeID},{Page}.html',
  'ContentPortalURL' => 'http://manage.test.com/publish/content.php/{IndexID},{Page}.html',
  'Pager' => '#default.php',
  'Editor' => 'default.php',
  'WorkFlow' => '0',
  'PermissionManageG' => '',
  'PermissionManageU' => '',
  'PermissionReadG' => '',
  'PermissionReadU' => '',
  'PermissionWriteG' => '',
  'PermissionWriteU' => '',
  'PermissionApproveG' => '',
  'PermissionApproveU' => '',
  'PermissionPublishG' => '',
  'PermissionPublishU' => '',
  'PermissionInherit' => '0',
  'show' => '1',
  'CreationUserID' => '1',
  'SubNodeID' => '3%70%71%72%73%74%75%76%77%78%79%80%81%82%83%84%55%69%56%57%58%59%60%61%62%63%64%65%66%67%68%89%90%91%92%93%94%95%96%97%98%99%100%101%102%103',
  'ParentNodeID' => '1%3',
  'Nav' => 'a:2:{i:0;a:2:{s:6:"NodeID";s:1:"1";s:4:"Name";s:11:"91yxq游戏";}i:1;a:2:{s:6:"NodeID";s:1:"3";s:4:"Name";s:17:"91yxq游戏官网";}}',
  'URL' => NULL,
  'Navigation' => 
  array (
    0 => 
    array (
      'NodeID' => '1',
      'Name' => '91yxq游戏',
      'URL' => '/index.html',
      'NodeName' => '91yxq游戏',
      'NodeURL' => '/index.html',
    ),
    1 => 
    array (
      'NodeID' => '3',
      'Name' => '91yxq游戏官网',
      'URL' => NULL,
      'NodeName' => '91yxq游戏官网',
      'NodeURL' => NULL,
    ),
  ),
);
?>