<?php
//CMS cache file, DO NOT modify me!
//Created on December 29, 2016, 20:13

$NodeInfo = array (
  'NodeID' => '76',
  'NodeGUID' => '91yxq.zwx.ad',
  'TableID' => '1',
  'ParentID' => '70',
  'RootID' => '0',
  'InheritNodeID' => '0',
  'NodeType' => '1',
  'NodeSort' => '0',
  'Name' => '滚屏公告',
  'ContentPSN' => '',
  'ContentURL' => '',
  'ResourcePSN' => '{PSN:2}/rsc/games/zwx/ad',
  'ResourceURL' => '{PSN-URL:2}/rsc/games/zwx/ad',
  'PublishMode' => '1',
  'IndexTpl' => NULL,
  'IndexName' => NULL,
  'ContentTpl' => NULL,
  'ImageTpl' => NULL,
  'SubDir' => NULL,
  'PublishFileFormat' => NULL,
  'IsComment' => '0',
  'CommentLength' => NULL,
  'IsPrint' => '0',
  'IsGrade' => '0',
  'IsMail' => '0',
  'Disabled' => '0',
  'AutoPublish' => '2',
  'IndexPortalURL' => 'http://91yxq.com/publish/index.php/{NodeID},{Page}.html',
  'ContentPortalURL' => 'http://91yxq.com/publish/content.php/{IndexID},{Page}.html',
  'Pager' => '#default.php',
  'Editor' => 'default.php',
  'WorkFlow' => '0',
  'PermissionManageG' => NULL,
  'PermissionManageU' => NULL,
  'PermissionReadG' => NULL,
  'PermissionReadU' => NULL,
  'PermissionWriteG' => NULL,
  'PermissionWriteU' => NULL,
  'PermissionApproveG' => NULL,
  'PermissionApproveU' => NULL,
  'PermissionPublishG' => NULL,
  'PermissionPublishU' => NULL,
  'PermissionInherit' => NULL,
  'show' => '1',
  'CreationUserID' => '1',
  'SubNodeID' => '76',
  'ParentNodeID' => '1%3%70%76',
  'Nav' => 'a:4:{i:0;a:2:{s:6:"NodeID";s:1:"1";s:4:"Name";s:13:"91yxq游戏";}i:1;a:2:{s:6:"NodeID";s:1:"3";s:4:"Name";s:19:"91yxq游戏官网";}i:2;a:2:{s:6:"NodeID";s:2:"70";s:4:"Name";s:9:"醉武侠";}i:3;a:2:{s:6:"NodeID";s:2:"76";s:4:"Name";s:12:"滚屏公告";}}',
  'URL' => '/',
  'Navigation' => 
  array (
    0 => 
    array (
      'NodeID' => '1',
      'Name' => '91yxq游戏',
      'URL' => '/index.html',
      'NodeName' => '91yxq游戏',
      'NodeURL' => '/index.html',
    ),
    1 => 
    array (
      'NodeID' => '3',
      'Name' => '91yxq游戏官网',
      'URL' => NULL,
      'NodeName' => '91yxq游戏官网',
      'NodeURL' => NULL,
    ),
    2 => 
    array (
      'NodeID' => '70',
      'Name' => '醉武侠',
      'URL' => 'http://www.91yxq.com/zwx/index.html',
      'NodeName' => '醉武侠',
      'NodeURL' => 'http://www.91yxq.com/zwx/index.html',
    ),
    3 => 
    array (
      'NodeID' => '76',
      'Name' => '滚屏公告',
      'URL' => '/',
      'NodeName' => '滚屏公告',
      'NodeURL' => '/',
    ),
  ),
);
?>