<?php
//CMS cache file, DO NOT modify me!
//Created on December 29, 2016, 20:41

$NodeInfo = array (
  'NodeID' => '17',
  'NodeGUID' => '91yxq.www.doc.aboutus',
  'TableID' => '1',
  'ParentID' => '10',
  'RootID' => '0',
  'InheritNodeID' => '0',
  'NodeType' => '1',
  'NodeSort' => '0',
  'Name' => '关于我们',
  'ContentPSN' => '{PSN:1}/doc',
  'ContentURL' => '{PSN-URL:1}/doc',
  'ResourcePSN' => '{PSN:2}/rsc/www/doccenter',
  'ResourceURL' => '{PSN-URL:2}/rsc/www/doccenter',
  'PublishMode' => '1',
  'IndexTpl' => '',
  'IndexName' => 'aboutus.html',
  'ContentTpl' => '/www/doc/aboutus.html',
  'ImageTpl' => '',
  'SubDir' => '',
  'PublishFileFormat' => 'aboutus.html',
  'IsComment' => '0',
  'CommentLength' => NULL,
  'IsPrint' => '0',
  'IsGrade' => '0',
  'IsMail' => '0',
  'Disabled' => '0',
  'AutoPublish' => '2',
  'IndexPortalURL' => 'http://manage.test.com/publish/index.php/{NodeID},{Page}.html',
  'ContentPortalURL' => 'http://manage.test.com/publish/content.php/{IndexID},{Page}.html',
  'Pager' => '#default.php',
  'Editor' => 'default.php',
  'WorkFlow' => '0',
  'PermissionManageG' => '',
  'PermissionManageU' => '',
  'PermissionReadG' => '',
  'PermissionReadU' => '',
  'PermissionWriteG' => '',
  'PermissionWriteU' => '',
  'PermissionApproveG' => '',
  'PermissionApproveU' => '',
  'PermissionPublishG' => '',
  'PermissionPublishU' => '',
  'PermissionInherit' => '0',
  'show' => '1',
  'CreationUserID' => '1',
  'SubNodeID' => '17',
  'ParentNodeID' => '1%2%10%17',
  'Nav' => 'a:4:{i:0;a:2:{s:6:"NodeID";s:1:"1";s:4:"Name";s:13:"91yxq游戏";}i:1;a:2:{s:6:"NodeID";s:1:"2";s:4:"Name";s:13:"91yxq平台";}i:2;a:2:{s:6:"NodeID";s:2:"10";s:4:"Name";s:12:"文档中心";}i:3;a:2:{s:6:"NodeID";s:2:"17";s:4:"Name";s:12:"关于我们";}}',
  'URL' => 'http://www.91yxq.com/doc/aboutus.html',
  'Navigation' => 
  array (
    0 => 
    array (
      'NodeID' => '1',
      'Name' => '91yxq游戏',
      'URL' => '/index.html',
      'NodeName' => '91yxq游戏',
      'NodeURL' => '/index.html',
    ),
    1 => 
    array (
      'NodeID' => '2',
      'Name' => '91yxq平台',
      'URL' => 'http://www.91yxq.com/index.html',
      'NodeName' => '91yxq平台',
      'NodeURL' => 'http://www.91yxq.com/index.html',
    ),
    2 => 
    array (
      'NodeID' => '10',
      'Name' => '文档中心',
      'URL' => NULL,
      'NodeName' => '文档中心',
      'NodeURL' => NULL,
    ),
    3 => 
    array (
      'NodeID' => '17',
      'Name' => '关于我们',
      'URL' => 'http://www.91yxq.com/doc/aboutus.html',
      'NodeName' => '关于我们',
      'NodeURL' => 'http://www.91yxq.com/doc/aboutus.html',
    ),
  ),
);
?>