<?php
//CMS cache file, DO NOT modify me!
//Created on December 29, 2016, 19:23

$NodeInfo = array (
  'NodeID' => '101',
  'NodeGUID' => '91yxq.msb.xsk',
  'TableID' => '1',
  'ParentID' => '89',
  'RootID' => '0',
  'InheritNodeID' => '0',
  'NodeType' => '1',
  'NodeSort' => '0',
  'Name' => '新手卡',
  'ContentPSN' => '{PSN:8}/xsk',
  'ContentURL' => '{PSN-URL:8}/xsk',
  'ResourcePSN' => '{PSN:8}/rsc/games/msb/xsk',
  'ResourceURL' => '{PSN-URL:8}/rsc/games/cqby/xsk',
  'PublishMode' => '1',
  'IndexTpl' => '/www/games/msb/xsk.html',
  'IndexName' => 'index.html',
  'ContentTpl' => NULL,
  'ImageTpl' => NULL,
  'SubDir' => NULL,
  'PublishFileFormat' => 'index.html',
  'IsComment' => '0',
  'CommentLength' => NULL,
  'IsPrint' => '0',
  'IsGrade' => '0',
  'IsMail' => '0',
  'Disabled' => '0',
  'AutoPublish' => '2',
  'IndexPortalURL' => 'http://91yxq.com/publish/index.php/{NodeID},{Page}.html',
  'ContentPortalURL' => 'http://91yxq.com/publish/content.php/{IndexID},{Page}.html',
  'Pager' => '#default.php',
  'Editor' => 'default.php',
  'WorkFlow' => '0',
  'PermissionManageG' => NULL,
  'PermissionManageU' => NULL,
  'PermissionReadG' => NULL,
  'PermissionReadU' => NULL,
  'PermissionWriteG' => NULL,
  'PermissionWriteU' => NULL,
  'PermissionApproveG' => NULL,
  'PermissionApproveU' => NULL,
  'PermissionPublishG' => NULL,
  'PermissionPublishU' => NULL,
  'PermissionInherit' => NULL,
  'show' => '1',
  'CreationUserID' => '1',
  'SubNodeID' => '101',
  'ParentNodeID' => '1%3%89%101',
  'Nav' => 'a:4:{i:0;a:2:{s:6:"NodeID";s:1:"1";s:4:"Name";s:13:"91yxq游戏";}i:1;a:2:{s:6:"NodeID";s:1:"3";s:4:"Name";s:19:"91yxq游戏官网";}i:2;a:2:{s:6:"NodeID";s:2:"89";s:4:"Name";s:9:"魔神变";}i:3;a:2:{s:6:"NodeID";s:3:"101";s:4:"Name";s:9:"新手卡";}}',
  'URL' => 'http://www.91yxq.com/msb/xsk/index.html',
  'Navigation' => 
  array (
    0 => 
    array (
      'NodeID' => '1',
      'Name' => '91yxq游戏',
      'URL' => '/index.html',
      'NodeName' => '91yxq游戏',
      'NodeURL' => '/index.html',
    ),
    1 => 
    array (
      'NodeID' => '3',
      'Name' => '91yxq游戏官网',
      'URL' => NULL,
      'NodeName' => '91yxq游戏官网',
      'NodeURL' => NULL,
    ),
    2 => 
    array (
      'NodeID' => '89',
      'Name' => '魔神变',
      'URL' => 'http://www.91yxq.com/msb/index.html',
      'NodeName' => '魔神变',
      'NodeURL' => 'http://www.91yxq.com/msb/index.html',
    ),
    3 => 
    array (
      'NodeID' => '101',
      'Name' => '新手卡',
      'URL' => 'http://www.91yxq.com/msb/xsk/index.html',
      'NodeName' => '新手卡',
      'NodeURL' => 'http://www.91yxq.com/msb/xsk/index.html',
    ),
  ),
);
?>