<?php
//CMS cache file, DO NOT modify me!
//Created on March 31, 2017, 16:58

$NodeInfo = array (
  'NodeID' => '5',
  'NodeGUID' => '91yxq.www.public',
  'TableID' => '1',
  'ParentID' => '2',
  'RootID' => '0',
  'InheritNodeID' => '0',
  'NodeType' => '1',
  'NodeSort' => '0',
  'Name' => '公共部分',
  'ContentPSN' => '',
  'ContentURL' => '',
  'ResourcePSN' => '',
  'ResourceURL' => '',
  'PublishMode' => '0',
  'IndexTpl' => '',
  'IndexName' => 'index.html',
  'ContentTpl' => '',
  'ImageTpl' => '',
  'SubDir' => 'Y-m-d',
  'PublishFileFormat' => '{TimeStamp}d{ContentID}.html',
  'IsComment' => '0',
  'CommentLength' => NULL,
  'IsPrint' => '0',
  'IsGrade' => '0',
  'IsMail' => '0',
  'Disabled' => '0',
  'AutoPublish' => '2',
  'IndexPortalURL' => 'http://manage.test.com/publish/index.php/{NodeID},{Page}.html',
  'ContentPortalURL' => 'http://manage.test.com/publish/content.php/{IndexID},{Page}.html',
  'Pager' => '#default.php',
  'Editor' => 'default.php',
  'WorkFlow' => '0',
  'PermissionManageG' => '',
  'PermissionManageU' => '',
  'PermissionReadG' => '',
  'PermissionReadU' => '',
  'PermissionWriteG' => '',
  'PermissionWriteU' => '',
  'PermissionApproveG' => '',
  'PermissionApproveU' => '',
  'PermissionPublishG' => '',
  'PermissionPublishU' => '',
  'PermissionInherit' => '0',
  'show' => '1',
  'CreationUserID' => '1',
  'SubNodeID' => '5%4%21%22%23%24%25%26%27%28%29%30%31',
  'ParentNodeID' => '1%2%5',
  'Nav' => 'a:3:{i:0;a:2:{s:6:"NodeID";s:1:"1";s:4:"Name";s:11:"91yxq游戏";}i:1;a:2:{s:6:"NodeID";s:1:"2";s:4:"Name";s:11:"91yxq平台";}i:2;a:2:{s:6:"NodeID";s:1:"5";s:4:"Name";s:12:"公共部分";}}',
  'URL' => NULL,
  'Navigation' => 
  array (
    0 => 
    array (
      'NodeID' => '1',
      'Name' => '91yxq游戏',
      'URL' => '/index.html',
      'NodeName' => '91yxq游戏',
      'NodeURL' => '/index.html',
    ),
    1 => 
    array (
      'NodeID' => '2',
      'Name' => '91yxq平台',
      'URL' => 'http://www.demo.com/index.html',
      'NodeName' => '91yxq平台',
      'NodeURL' => 'http://www.demo.com/index.html',
    ),
    2 => 
    array (
      'NodeID' => '5',
      'Name' => '公共部分',
      'URL' => NULL,
      'NodeName' => '公共部分',
      'NodeURL' => NULL,
    ),
  ),
);
?>