<?php
//CMS cache file, DO NOT modify me!
//Created on December 29, 2016, 20:40

$NodeInfo = array (
  'NodeID' => '12',
  'NodeGUID' => '91yxq.www.newscenter.tjhd',
  'TableID' => '1',
  'ParentID' => '8',
  'RootID' => '0',
  'InheritNodeID' => '0',
  'NodeType' => '1',
  'NodeSort' => '0',
  'Name' => '推荐活动',
  'ContentPSN' => '{PSN:1}/news',
  'ContentURL' => '{PSN-URL:1}/news',
  'ResourcePSN' => '{PSN:2}/rsc/www/newscenter',
  'ResourceURL' => '{PSN-URL:2}/rsc/www/newscenter',
  'PublishMode' => '1',
  'IndexTpl' => '/www/news/news_list.html',
  'IndexName' => 'activity.html',
  'ContentTpl' => '/www/news/news_detail.html',
  'ImageTpl' => '',
  'SubDir' => 'Y/md',
  'PublishFileFormat' => '{ContentID}.html',
  'IsComment' => '0',
  'CommentLength' => NULL,
  'IsPrint' => '0',
  'IsGrade' => '0',
  'IsMail' => '0',
  'Disabled' => '0',
  'AutoPublish' => '2',
  'IndexPortalURL' => 'http://manage.test.com/publish/index.php/{NodeID},{Page}.html',
  'ContentPortalURL' => 'http://manage.test.com/publish/content.php/{IndexID},{Page}.html',
  'Pager' => '#default.php',
  'Editor' => 'default.php',
  'WorkFlow' => '0',
  'PermissionManageG' => '',
  'PermissionManageU' => '',
  'PermissionReadG' => '',
  'PermissionReadU' => '',
  'PermissionWriteG' => '',
  'PermissionWriteU' => '',
  'PermissionApproveG' => '',
  'PermissionApproveU' => '',
  'PermissionPublishG' => '',
  'PermissionPublishU' => '',
  'PermissionInherit' => '0',
  'show' => '1',
  'CreationUserID' => '1',
  'SubNodeID' => '12',
  'ParentNodeID' => '1%2%8%12',
  'Nav' => 'a:4:{i:0;a:2:{s:6:"NodeID";s:1:"1";s:4:"Name";s:13:"91yxq游戏";}i:1;a:2:{s:6:"NodeID";s:1:"2";s:4:"Name";s:13:"91yxq平台";}i:2;a:2:{s:6:"NodeID";s:1:"8";s:4:"Name";s:12:"新闻中心";}i:3;a:2:{s:6:"NodeID";s:2:"12";s:4:"Name";s:12:"推荐活动";}}',
  'URL' => 'http://www.91yxq.com/news/activity.html',
  'Navigation' => 
  array (
    0 => 
    array (
      'NodeID' => '1',
      'Name' => '91yxq游戏',
      'URL' => '/index.html',
      'NodeName' => '91yxq游戏',
      'NodeURL' => '/index.html',
    ),
    1 => 
    array (
      'NodeID' => '2',
      'Name' => '91yxq平台',
      'URL' => 'http://www.91yxq.com/index.html',
      'NodeName' => '91yxq平台',
      'NodeURL' => 'http://www.91yxq.com/index.html',
    ),
    2 => 
    array (
      'NodeID' => '8',
      'Name' => '新闻中心',
      'URL' => NULL,
      'NodeName' => '新闻中心',
      'NodeURL' => NULL,
    ),
    3 => 
    array (
      'NodeID' => '12',
      'Name' => '推荐活动',
      'URL' => 'http://www.91yxq.com/news/activity.html',
      'NodeName' => '推荐活动',
      'NodeURL' => 'http://www.91yxq.com/news/activity.html',
    ),
  ),
);
?>