<?php
//CMS cache file, DO NOT modify me!
//Created on December 29, 2016, 19:23

$NodeInfo = array (
  'NodeID' => '37',
  'NodeGUID' => '91yxq.cqby',
  'TableID' => '1',
  'ParentID' => '3',
  'RootID' => '0',
  'InheritNodeID' => '0',
  'NodeType' => '1',
  'NodeSort' => '0',
  'Name' => '传奇霸业',
  'ContentPSN' => '{PSN:3}',
  'ContentURL' => '{PSN-URL:3}',
  'ResourcePSN' => '{PSN:2}/rsc/games/cqby',
  'ResourceURL' => '{PSN-URL:2}/rsc/games/cqby',
  'PublishMode' => '1',
  'IndexTpl' => '/www/games/cqby/index.html',
  'IndexName' => 'index.html',
  'ContentTpl' => '',
  'ImageTpl' => '',
  'SubDir' => '',
  'PublishFileFormat' => 'index.html',
  'IsComment' => '0',
  'CommentLength' => NULL,
  'IsPrint' => '0',
  'IsGrade' => '0',
  'IsMail' => '0',
  'Disabled' => '0',
  'AutoPublish' => '2',
  'IndexPortalURL' => 'http://manage.test.com/publish/index.php/{NodeID},{Page}.html',
  'ContentPortalURL' => 'http://manage.test.com/publish/content.php/{IndexID},{Page}.html',
  'Pager' => '#default.php',
  'Editor' => 'default.php',
  'WorkFlow' => '0',
  'PermissionManageG' => '',
  'PermissionManageU' => '',
  'PermissionReadG' => '',
  'PermissionReadU' => '',
  'PermissionWriteG' => '',
  'PermissionWriteU' => '',
  'PermissionApproveG' => '',
  'PermissionApproveU' => '',
  'PermissionPublishG' => '',
  'PermissionPublishU' => '',
  'PermissionInherit' => '0',
  'show' => '1',
  'CreationUserID' => '1',
  'SubNodeID' => '37%38%42%43%44%45%46%47%48%49%50%51%52%53%54',
  'ParentNodeID' => '1%3%37',
  'Nav' => 'a:3:{i:0;a:2:{s:6:"NodeID";s:1:"1";s:4:"Name";s:13:"91yxq游戏";}i:1;a:2:{s:6:"NodeID";s:1:"3";s:4:"Name";s:19:"91yxq游戏官网";}i:2;a:2:{s:6:"NodeID";s:2:"37";s:4:"Name";s:12:"传奇霸业";}}',
  'URL' => 'http://www.91yxq.com/cqby/index.html',
  'Navigation' => 
  array (
    0 => 
    array (
      'NodeID' => '1',
      'Name' => '91yxq游戏',
      'URL' => '/index.html',
      'NodeName' => '91yxq游戏',
      'NodeURL' => '/index.html',
    ),
    1 => 
    array (
      'NodeID' => '3',
      'Name' => '91yxq游戏官网',
      'URL' => NULL,
      'NodeName' => '91yxq游戏官网',
      'NodeURL' => NULL,
    ),
    2 => 
    array (
      'NodeID' => '37',
      'Name' => '传奇霸业',
      'URL' => 'http://www.91yxq.com/cqby/index.html',
      'NodeName' => '传奇霸业',
      'NodeURL' => 'http://www.91yxq.com/cqby/index.html',
    ),
  ),
);
?>