<?php
//CMS cache file, DO NOT modify me!
//Created on December 29, 2016, 20:19

$NodeInfo = array (
  'NodeID' => '33',
  'NodeGUID' => '91yxq.www.index.hotgame',
  'TableID' => '7',
  'ParentID' => '6',
  'RootID' => '0',
  'InheritNodeID' => '0',
  'NodeType' => '1',
  'NodeSort' => '0',
  'Name' => '热门游戏',
  'ContentPSN' => '',
  'ContentURL' => '',
  'ResourcePSN' => '{PSN:2}/rsc/www/index/hotgame',
  'ResourceURL' => '{PSN-URL:2}/rsc/www/index/hotgame',
  'PublishMode' => '1',
  'IndexTpl' => '',
  'IndexName' => '',
  'ContentTpl' => '',
  'ImageTpl' => '',
  'SubDir' => '',
  'PublishFileFormat' => '',
  'IsComment' => '0',
  'CommentLength' => NULL,
  'IsPrint' => '0',
  'IsGrade' => '0',
  'IsMail' => '0',
  'Disabled' => '0',
  'AutoPublish' => '2',
  'IndexPortalURL' => 'http://manage.test.com/publish/index.php/{NodeID},{Page}.html',
  'ContentPortalURL' => 'http://manage.test.com/publish/content.php/{IndexID},{Page}.html',
  'Pager' => '#default.php',
  'Editor' => 'default.php',
  'WorkFlow' => '0',
  'PermissionManageG' => '',
  'PermissionManageU' => '',
  'PermissionReadG' => '',
  'PermissionReadU' => '',
  'PermissionWriteG' => '',
  'PermissionWriteU' => '',
  'PermissionApproveG' => '',
  'PermissionApproveU' => '',
  'PermissionPublishG' => '',
  'PermissionPublishU' => '',
  'PermissionInherit' => '0',
  'show' => '1',
  'CreationUserID' => '1',
  'SubNodeID' => '33',
  'ParentNodeID' => '1%2%6%33',
  'Nav' => 'a:4:{i:0;a:2:{s:6:"NodeID";s:1:"1";s:4:"Name";s:13:"91yxq游戏";}i:1;a:2:{s:6:"NodeID";s:1:"2";s:4:"Name";s:13:"91yxq平台";}i:2;a:2:{s:6:"NodeID";s:1:"6";s:4:"Name";s:6:"首页";}i:3;a:2:{s:6:"NodeID";s:2:"33";s:4:"Name";s:12:"热门游戏";}}',
  'URL' => '/',
  'Navigation' => 
  array (
    0 => 
    array (
      'NodeID' => '1',
      'Name' => '91yxq游戏',
      'URL' => '/index.html',
      'NodeName' => '91yxq游戏',
      'NodeURL' => '/index.html',
    ),
    1 => 
    array (
      'NodeID' => '2',
      'Name' => '91yxq平台',
      'URL' => 'http://www.91yxq.com/index.html',
      'NodeName' => '91yxq平台',
      'NodeURL' => 'http://www.91yxq.com/index.html',
    ),
    2 => 
    array (
      'NodeID' => '6',
      'Name' => '首页',
      'URL' => 'http://www.91yxq.com/index_test.html',
      'NodeName' => '首页',
      'NodeURL' => 'http://www.91yxq.com/index_test.html',
    ),
    3 => 
    array (
      'NodeID' => '33',
      'Name' => '热门游戏',
      'URL' => '/',
      'NodeName' => '热门游戏',
      'NodeURL' => '/',
    ),
  ),
);
?>