<?php
//CMS cache file, DO NOT modify me!
//Created on March 17, 2017, 19:39

$SYS_ENV = array (
  'AutoPageLen' => '2000',
  'enable_gzip' => '0',
  'sessionTimeout' => '120',
  'ContentPageNum' => '15',
  'SearchPageNum' => '15',
  'CollectionPageNum' => '15',
  'templatePath' => '../templates',
  'sysname' => 'http://fbsys.demo.com/cms/',
  'DisplayPublishCount' => '1',
  'DisplayNodeID' => '1',
  'backupPath' => '../backup',
  'uploadPath' => NULL,
  'uploadUrl' => NULL,
  'smtp_host' => '',
  'smtp_username' => '',
  'smtp_password' => '',
  'smtp_auth' => '',
  'upImgType' => 'png|gif|jpeg|jpg|bmp',
  'upImgSize' => '600',
  'upFlashSize' => '10000',
  'upAttachType' => 'zip|rar|doc|xls|txt',
  'upAttachSize' => '1000',
  'tasktimeout' => '1489732777',
  'openTask' => '0',
  'sitename' => NULL,
  'is_safe_mode' => '',
  'ftp_server' => '',
  'ftp_server_port' => '',
  'ftp_user_name' => '',
  'ftp_user_pass' => '',
  'ftp_cms_admin_path' => '',
  'localImgIgnoreURL' => '{localhost}{127.0.0.1}{localhost}{admin.demo.com}{fbsys.demo.com}{image.demo.com}',
  'ResourcePath' => '../resource',
  'language' => '',
  'isLogLogin' => '1',
  'isLogAdmin' => '1',
  'LoginTryTime' => '15',
  'LoginTryCount' => '5',
  'WaterMarkPosition' => '9',
  'WaterMarkImgPath' => '../html/WaterMark.gif',
  'EnableWaterMark' => '0',
  'EnableEditorWaterMark' => '0',
  'EnableCLWaterMark' => '0',
  'ContentViewMode' => '1',
  'CollectionViewMode' => '1',
  'ContributionViewMode' => '1',
  'DefaultResourcePSN' => '',
  'DefaultResourcePSNURL' => '',
  'DefaultContentPSN' => '',
  'DefaultContentPSNURL' => '',
  'DialogFitXP' => '1',
  'AutoRefreshTree' => '0',
  'hostname' => NULL,
  'publishResourceNum' => NULL,
  'ResourceNum' => NULL,
  'smtp_from_email' => NULL,
  'upload_attach_num' => NULL,
  'upload_flash_num' => NULL,
  'version' => 'CMSware 2.5 Plus Stable',
);
?>