<?php
//CMS cache file, DO NOT modify me!
//Created on March 17, 2017, 19:39

$CONTENT_MODEL_INFO = array (
  1 => 
  array (
    'TableID' => '1',
    'Name' => '新闻系统模型',
    'DSNID' => '0',
    'Model' => 
    array (
      0 => 
      array (
        'ContentFieldID' => '60',
        'TableID' => '1',
        'FieldTitle' => '标题高亮前缀',
        'FieldName' => 'TitlePrefix',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => '',
        'FieldInputFilter' => '',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '如《新闻》、《公告》、《活动》、《游戏名称》等',
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      1 => 
      array (
        'ContentFieldID' => '61',
        'TableID' => '1',
        'FieldTitle' => '标题前缀颜色',
        'FieldName' => 'TitlePrefixColor',
        'FieldType' => 'varchar',
        'FieldSize' => '7',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => 'color',
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '1',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      2 => 
      array (
        'ContentFieldID' => '1',
        'TableID' => '1',
        'FieldTitle' => '标题',
        'FieldName' => 'Title',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '新闻的标题',
        'FieldOrder' => '2',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '1',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      3 => 
      array (
        'ContentFieldID' => '2',
        'TableID' => '1',
        'FieldTitle' => '标题颜色',
        'FieldName' => 'TitleColor',
        'FieldType' => 'varchar',
        'FieldSize' => '7',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => 'color',
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '3',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '0',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      4 => 
      array (
        'ContentFieldID' => '3',
        'TableID' => '1',
        'FieldTitle' => '作者',
        'FieldName' => 'Author',
        'FieldType' => 'varchar',
        'FieldSize' => '20',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '新闻的原作者',
        'FieldOrder' => '4',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      5 => 
      array (
        'ContentFieldID' => '4',
        'TableID' => '1',
        'FieldTitle' => '新闻图片',
        'FieldName' => 'Photo',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => 'upload',
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '5',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      6 => 
      array (
        'ContentFieldID' => '5',
        'TableID' => '1',
        'FieldTitle' => '顶部flash',
        'FieldName' => 'TopFlash',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => '',
        'FieldInputFilter' => '',
        'FieldInputPicker' => 'flash',
        'FieldInputTpl' => '',
        'FieldDescription' => '顶部flash',
        'FieldOrder' => '6',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      7 => 
      array (
        'ContentFieldID' => '6',
        'TableID' => '1',
        'FieldTitle' => '新闻内容',
        'FieldName' => 'Content',
        'FieldType' => 'longtext',
        'FieldSize' => '',
        'FieldInput' => 'CKEditor',
        'FieldDefaultValue' => '',
        'FieldInputFilter' => '',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '',
        'FieldOrder' => '7',
        'FieldListDisplay' => '0',
        'IsMainField' => '1',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      8 => 
      array (
        'ContentFieldID' => '7',
        'TableID' => '1',
        'FieldTitle' => '关键字',
        'FieldName' => 'Keywords',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '8',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '0',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      9 => 
      array (
        'ContentFieldID' => '8',
        'TableID' => '1',
        'FieldTitle' => '副标题',
        'FieldName' => 'SubTitle',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '9',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      10 => 
      array (
        'ContentFieldID' => '9',
        'TableID' => '1',
        'FieldTitle' => '来源站点名称',
        'FieldName' => 'FromSite',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => '',
        'FieldInputFilter' => '',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '',
        'FieldOrder' => '10',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      11 => 
      array (
        'ContentFieldID' => '13',
        'TableID' => '1',
        'FieldTitle' => '来源站点地址',
        'FieldName' => 'FromSiteUrl',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '11',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      12 => 
      array (
        'ContentFieldID' => '10',
        'TableID' => '1',
        'FieldTitle' => '责任编辑',
        'FieldName' => 'Editor',
        'FieldType' => 'varchar',
        'FieldSize' => '20',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '新闻编辑',
        'FieldOrder' => '12',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      13 => 
      array (
        'ContentFieldID' => '11',
        'TableID' => '1',
        'FieldTitle' => '自定义相关文章 ',
        'FieldName' => 'CustomLinks',
        'FieldType' => 'contentlink',
        'FieldSize' => NULL,
        'FieldInput' => 'select',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '13',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '0',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      14 => 
      array (
        'ContentFieldID' => '12',
        'TableID' => '1',
        'FieldTitle' => '简介',
        'FieldName' => 'Intro',
        'FieldType' => 'text',
        'FieldSize' => NULL,
        'FieldInput' => 'textaera',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '14',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
    ),
    'TitleField' => 'Title',
    'MainField' => 'Content',
  ),
  2 => 
  array (
    'TableID' => '2',
    'Name' => '图片系统模型',
    'DSNID' => '0',
    'TitleField' => 'Title',
    'Model' => 
    array (
      0 => 
      array (
        'ContentFieldID' => '14',
        'TableID' => '2',
        'FieldTitle' => '图片名称',
        'FieldName' => 'Title',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '1',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      1 => 
      array (
        'ContentFieldID' => '15',
        'TableID' => '2',
        'FieldTitle' => '图片作者',
        'FieldName' => 'Author',
        'FieldType' => 'varchar',
        'FieldSize' => '20',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '上传图片的用户帐号',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      2 => 
      array (
        'ContentFieldID' => '16',
        'TableID' => '2',
        'FieldTitle' => '缩略图',
        'FieldName' => 'Thumb',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => 'upload',
        'FieldInputTpl' => NULL,
        'FieldDescription' => '(<font color="red"><b>游戏截图、玩家相册必须同时上传 缩略图！！！尺寸大小以官网为准，不大于15K，若不符合要求...【严重】</b></font>)',
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      3 => 
      array (
        'ContentFieldID' => '17',
        'TableID' => '2',
        'FieldTitle' => '上传图片',
        'FieldName' => 'Photo',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => 'upload',
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      4 => 
      array (
        'ContentFieldID' => '18',
        'TableID' => '2',
        'FieldTitle' => '图片内容',
        'FieldName' => 'Content',
        'FieldType' => 'longtext',
        'FieldSize' => NULL,
        'FieldInput' => 'CKEditor',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '1',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      5 => 
      array (
        'ContentFieldID' => '19',
        'TableID' => '2',
        'FieldTitle' => '图片简介',
        'FieldName' => 'Intro',
        'FieldType' => 'text',
        'FieldSize' => NULL,
        'FieldInput' => 'RichEditor',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      6 => 
      array (
        'ContentFieldID' => '20',
        'TableID' => '2',
        'FieldTitle' => '关键字',
        'FieldName' => 'KeyWords',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
    ),
    'MainField' => 'Content',
  ),
  3 => 
  array (
    'TableID' => '3',
    'Name' => '友情链接模型',
    'DSNID' => '0',
    'TitleField' => 'Title',
    'Model' => 
    array (
      0 => 
      array (
        'ContentFieldID' => '21',
        'TableID' => '3',
        'FieldTitle' => '链接标题',
        'FieldName' => 'Title',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => '',
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '文本链接的文本内容，必选',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '1',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      1 => 
      array (
        'ContentFieldID' => '22',
        'TableID' => '3',
        'FieldTitle' => '链接图片',
        'FieldName' => 'Image',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => '',
        'FieldInputFilter' => '',
        'FieldInputPicker' => 'upload',
        'FieldInputTpl' => '',
        'FieldDescription' => '图片链接的图片，可选',
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      2 => 
      array (
        'ContentFieldID' => '23',
        'TableID' => '3',
        'FieldTitle' => '链接地址',
        'FieldName' => 'FriendLink',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => '',
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => 'url地址，必选',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '1',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      3 => 
      array (
        'ContentFieldID' => '59',
        'TableID' => '3',
        'FieldTitle' => '排序优先级',
        'FieldName' => 'SortPriority',
        'FieldType' => 'int',
        'FieldSize' => '10',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'num',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '按此数值从大到小排序',
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
    ),
    'MainField' => 'FriendLink',
  ),
  4 => 
  array (
    'TableID' => '4',
    'Name' => '数据字典模型1',
    'DSNID' => '0',
    'TitleField' => 'DataId',
    'Model' => 
    array (
      0 => 
      array (
        'ContentFieldID' => '24',
        'TableID' => '4',
        'FieldTitle' => '数据id',
        'FieldName' => 'DataId',
        'FieldType' => 'int',
        'FieldSize' => '10',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'unique',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '限数字，且不能重复',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '1',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      1 => 
      array (
        'ContentFieldID' => '25',
        'TableID' => '4',
        'FieldTitle' => '数据数值',
        'FieldName' => 'DataValue',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '1',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
    ),
    'MainField' => 'DataValue',
  ),
  5 => 
  array (
    'TableID' => '5',
    'Name' => '游戏列表模型',
    'DSNID' => '0',
    'Model' => 
    array (
      0 => 
      array (
        'ContentFieldID' => '26',
        'TableID' => '5',
        'FieldTitle' => '所属游戏平台',
        'FieldName' => 'PlatformId',
        'FieldType' => 'int',
        'FieldSize' => '1',
        'FieldInput' => 'select',
        'FieldDefaultValue' => '1',
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '*必填 1:91yxq',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      1 => 
      array (
        'ContentFieldID' => '31',
        'TableID' => '5',
        'FieldTitle' => '游戏id',
        'FieldName' => 'GameId',
        'FieldType' => 'int',
        'FieldSize' => '10',
        'FieldInput' => 'text',
        'FieldDefaultValue' => '',
        'FieldInputFilter' => 'num',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '同一平台下，游戏id不允许重复',
        'FieldOrder' => '1',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      2 => 
      array (
        'ContentFieldID' => '32',
        'TableID' => '5',
        'FieldTitle' => '游戏名称',
        'FieldName' => 'GameName',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '2',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '1',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      3 => 
      array (
        'ContentFieldID' => '34',
        'TableID' => '5',
        'FieldTitle' => '游戏名称缩写',
        'FieldName' => 'ShortName',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => '',
        'FieldInputFilter' => '',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '游戏名的字母缩写',
        'FieldOrder' => '3',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      4 => 
      array (
        'ContentFieldID' => '27',
        'TableID' => '5',
        'FieldTitle' => '游戏人气指数',
        'FieldName' => 'GamePopularity',
        'FieldType' => 'int',
        'FieldSize' => '10',
        'FieldInput' => 'text',
        'FieldDefaultValue' => '',
        'FieldInputFilter' => 'num',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '游戏人气指数',
        'FieldOrder' => '4',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      5 => 
      array (
        'ContentFieldID' => '28',
        'TableID' => '5',
        'FieldTitle' => '游戏标签',
        'FieldName' => 'GameTag',
        'FieldType' => 'int',
        'FieldSize' => '1',
        'FieldInput' => 'select',
        'FieldDefaultValue' => '0;1;2;3',
        'FieldInputFilter' => '',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '0:无;1:最新;2:火爆;3:推荐',
        'FieldOrder' => '5',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
        'selectValue' => 
        array (
          0 => '0',
          1 => '1',
          2 => '2',
          3 => '3',
        ),
      ),
      6 => 
      array (
        'ContentFieldID' => '29',
        'TableID' => '5',
        'FieldTitle' => '游戏类型',
        'FieldName' => 'GameType',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'select',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '6',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      7 => 
      array (
        'ContentFieldID' => '30',
        'TableID' => '5',
        'FieldTitle' => '游戏类型id',
        'FieldName' => 'GameTypeId',
        'FieldType' => 'int',
        'FieldSize' => '10',
        'FieldInput' => 'select',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '7',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      8 => 
      array (
        'ContentFieldID' => '33',
        'TableID' => '5',
        'FieldTitle' => '游戏描述',
        'FieldName' => 'GameDescription',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'textaera',
        'FieldDefaultValue' => '',
        'FieldInputFilter' => '',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '',
        'FieldOrder' => '8',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      9 => 
      array (
        'ContentFieldID' => '35',
        'TableID' => '5',
        'FieldTitle' => '游戏官网地址',
        'FieldName' => 'GameWeb',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '9',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      10 => 
      array (
        'ContentFieldID' => '36',
        'TableID' => '5',
        'FieldTitle' => '礼包领取地址',
        'FieldName' => 'GiftUrl',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '10',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      11 => 
      array (
        'ContentFieldID' => '37',
        'TableID' => '5',
        'FieldTitle' => '服务器列表地址',
        'FieldName' => 'ServerUrl',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '11',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      12 => 
      array (
        'ContentFieldID' => '38',
        'TableID' => '5',
        'FieldTitle' => '广告入口地址',
        'FieldName' => 'AdUrl',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '12',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      13 => 
      array (
        'ContentFieldID' => '39',
        'TableID' => '5',
        'FieldTitle' => '是否停服',
        'FieldName' => 'ServiceStatus',
        'FieldType' => 'int',
        'FieldSize' => '1',
        'FieldInput' => 'radio',
        'FieldDefaultValue' => '1;0',
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '1:正常; 0：停服',
        'FieldOrder' => '13',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
        'selectValue' => 
        array (
          0 => '1',
          1 => '0',
        ),
      ),
      14 => 
      array (
        'ContentFieldID' => '55',
        'TableID' => '5',
        'FieldTitle' => '游戏题材',
        'FieldName' => 'GameTheme',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'select',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '14',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      15 => 
      array (
        'ContentFieldID' => '56',
        'TableID' => '5',
        'FieldTitle' => '游戏题材id',
        'FieldName' => 'GameThemeId',
        'FieldType' => 'int',
        'FieldSize' => '10',
        'FieldInput' => 'select',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'num',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '15',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      16 => 
      array (
        'ContentFieldID' => '57',
        'TableID' => '5',
        'FieldTitle' => '字母排序',
        'FieldName' => 'GameInitial',
        'FieldType' => 'varchar',
        'FieldSize' => '5',
        'FieldInput' => 'select',
        'FieldDefaultValue' => '',
        'FieldInputFilter' => '',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '游戏名称首字母所在',
        'FieldOrder' => '16',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      17 => 
      array (
        'ContentFieldID' => '58',
        'TableID' => '5',
        'FieldTitle' => '字母排序id',
        'FieldName' => 'GameInitialId',
        'FieldType' => 'int',
        'FieldSize' => '10',
        'FieldInput' => 'select',
        'FieldDefaultValue' => '',
        'FieldInputFilter' => '',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '',
        'FieldOrder' => '17',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
    ),
    'TitleField' => 'GameName',
  ),
  6 => 
  array (
    'TableID' => '6',
    'Name' => '开服列表模型',
    'DSNID' => '0',
    'Model' => 
    array (
      0 => 
      array (
        'ContentFieldID' => '40',
        'TableID' => '6',
        'FieldTitle' => '所属游戏平台',
        'FieldName' => 'PlatformId',
        'FieldType' => 'int',
        'FieldSize' => '1',
        'FieldInput' => 'select',
        'FieldDefaultValue' => '1',
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '*必填 1:91yxq',
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      1 => 
      array (
        'ContentFieldID' => '41',
        'TableID' => '6',
        'FieldTitle' => '游戏id',
        'FieldName' => 'GameId',
        'FieldType' => 'int',
        'FieldSize' => '10',
        'FieldInput' => 'select',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '*必选项',
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      2 => 
      array (
        'ContentFieldID' => '42',
        'TableID' => '6',
        'FieldTitle' => '服务器id',
        'FieldName' => 'ServerId',
        'FieldType' => 'int',
        'FieldSize' => '10',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'num',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '*必选项 ',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '1',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      3 => 
      array (
        'ContentFieldID' => '43',
        'TableID' => '6',
        'FieldTitle' => '服务器名称',
        'FieldName' => 'ServerName',
        'FieldType' => 'varchar',
        'FieldSize' => '20',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '*必选项 ',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '1',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      4 => 
      array (
        'ContentFieldID' => '44',
        'TableID' => '6',
        'FieldTitle' => '合服id',
        'FieldName' => 'MergeId',
        'FieldType' => 'int',
        'FieldSize' => '10',
        'FieldInput' => 'text',
        'FieldDefaultValue' => '0',
        'FieldInputFilter' => 'num',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '新增服务器时不用填此项',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      5 => 
      array (
        'ContentFieldID' => '45',
        'TableID' => '6',
        'FieldTitle' => '开服日期',
        'FieldName' => 'OpenDate',
        'FieldType' => 'varchar',
        'FieldSize' => '10',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => 'date',
        'FieldInputTpl' => NULL,
        'FieldDescription' => '格式2015-10-01',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      6 => 
      array (
        'ContentFieldID' => '46',
        'TableID' => '6',
        'FieldTitle' => '开服时间',
        'FieldName' => 'OpenTime',
        'FieldType' => 'varchar',
        'FieldSize' => '10',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '填写格式：00:00 (小时:分钟)',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      7 => 
      array (
        'ContentFieldID' => '47',
        'TableID' => '6',
        'FieldTitle' => '服务器状态',
        'FieldName' => 'ServerStatus',
        'FieldType' => 'int',
        'FieldSize' => '1',
        'FieldInput' => 'select',
        'FieldDefaultValue' => '0;1;2;3;4;5;',
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '0:停服,1:维护,2:待开,3:顺畅,4:火爆,5:爆满',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
        'selectValue' => 
        array (
          0 => '0',
          1 => '1',
          2 => '2',
          3 => '3',
          4 => '4',
          5 => '5',
          6 => '',
        ),
      ),
      8 => 
      array (
        'ContentFieldID' => '48',
        'TableID' => '6',
        'FieldTitle' => '显示位置',
        'FieldName' => 'ServerShow',
        'FieldType' => 'int',
        'FieldSize' => '1',
        'FieldInput' => 'select',
        'FieldDefaultValue' => '0;1;2;3;',
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '0:全部隐藏,1:仅游戏官网显示,2:仅平台显示,3:全部显示',
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
        'selectValue' => 
        array (
          0 => '0',
          1 => '1',
          2 => '2',
          3 => '3',
          4 => '',
        ),
      ),
    ),
    'TitleField' => 'ServerId',
    'MainField' => 'ServerName',
  ),
  7 => 
  array (
    'TableID' => '7',
    'Name' => '推广游戏模型',
    'DSNID' => '0',
    'Model' => 
    array (
      0 => 
      array (
        'ContentFieldID' => '49',
        'TableID' => '7',
        'FieldTitle' => '所属游戏平台',
        'FieldName' => 'PlatformId',
        'FieldType' => 'int',
        'FieldSize' => '1',
        'FieldInput' => 'select',
        'FieldDefaultValue' => '',
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '1:91yxq',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      1 => 
      array (
        'ContentFieldID' => '50',
        'TableID' => '7',
        'FieldTitle' => '游戏id',
        'FieldName' => 'GameId',
        'FieldType' => 'int',
        'FieldSize' => '10',
        'FieldInput' => 'select',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '1',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      2 => 
      array (
        'ContentFieldID' => '51',
        'TableID' => '7',
        'FieldTitle' => '游戏展示图片',
        'FieldName' => 'GameImg',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => 'upload',
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      3 => 
      array (
        'ContentFieldID' => '52',
        'TableID' => '7',
        'FieldTitle' => '游戏特色',
        'FieldName' => 'GameFeature',
        'FieldType' => 'text',
        'FieldSize' => '',
        'FieldInput' => 'textaera',
        'FieldDefaultValue' => '这是一款非常好玩的游戏',
        'FieldInputFilter' => '',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '推荐理由',
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '1',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      4 => 
      array (
        'ContentFieldID' => '53',
        'TableID' => '7',
        'FieldTitle' => '开服节点id',
        'FieldName' => 'ServerNodiID',
        'FieldType' => 'int',
        'FieldSize' => '10',
        'FieldInput' => 'text',
        'FieldDefaultValue' => '',
        'FieldInputFilter' => 'num',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '填该游戏开服列表节点旁边的数字',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      5 => 
      array (
        'ContentFieldID' => '54',
        'TableID' => '7',
        'FieldTitle' => '排序优先级',
        'FieldName' => 'SortPriority',
        'FieldType' => 'int',
        'FieldSize' => '10',
        'FieldInput' => 'text',
        'FieldDefaultValue' => '0',
        'FieldInputFilter' => 'num',
        'FieldInputPicker' => '',
        'FieldInputTpl' => '',
        'FieldDescription' => '填正整数，从大到小，为0不显示',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
    ),
    'TitleField' => 'GameId',
    'MainField' => 'GameFeature',
  ),
);
?>