<?php
//CMS cache file, DO NOT modify me!
//Created on March 17, 2017, 19:39

$NODE_LIST = array (
  1 => 
  array (
    'NodeID' => '1',
    'Name' => '91yxq游戏',
    'ParentID' => '0',
    'TableID' => '1',
    'PublishMode' => '1',
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => 'root',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  2 => 
  array (
    'NodeID' => '2',
    'Name' => '91yxq平台',
    'ParentID' => '1',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  5 => 
  array (
    'NodeID' => '5',
    'Name' => '公共部分',
    'ParentID' => '2',
    'TableID' => '1',
    'PublishMode' => '0',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.public',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  4 => 
  array (
    'NodeID' => '4',
    'Name' => '游戏列表',
    'ParentID' => '5',
    'TableID' => '5',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.gamelist',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  21 => 
  array (
    'NodeID' => '21',
    'Name' => '公共头-js(登录/游戏列表)',
    'ParentID' => '5',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.public.top_js',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  22 => 
  array (
    'NodeID' => '22',
    'Name' => '弹出层登录框-js',
    'ParentID' => '5',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.public.login_js',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  23 => 
  array (
    'NodeID' => '23',
    'Name' => '弹出层登陆框-html',
    'ParentID' => '5',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.public.login_html',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  24 => 
  array (
    'NodeID' => '24',
    'Name' => '数据字典-游戏类型',
    'ParentID' => '5',
    'TableID' => '4',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.public.gametype',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  25 => 
  array (
    'NodeID' => '25',
    'Name' => '友情链接-js',
    'ParentID' => '5',
    'TableID' => '3',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.public.friendlylink',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  26 => 
  array (
    'NodeID' => '26',
    'Name' => '开服列表框-js',
    'ParentID' => '5',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.public.svrlistbox',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  27 => 
  array (
    'NodeID' => '27',
    'Name' => '推荐活动框-js',
    'ParentID' => '5',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.public.activitybox',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  28 => 
  array (
    'NodeID' => '28',
    'Name' => '公共页脚-js',
    'ParentID' => '5',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.public.footer',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  29 => 
  array (
    'NodeID' => '29',
    'Name' => '客服中心框-js',
    'ParentID' => '5',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.public.kfzx',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  30 => 
  array (
    'NodeID' => '30',
    'Name' => '数据字典-游戏题材',
    'ParentID' => '5',
    'TableID' => '4',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.public.gametheme',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  31 => 
  array (
    'NodeID' => '31',
    'Name' => '数据字典-首字母归类',
    'ParentID' => '5',
    'TableID' => '4',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.public.initial',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  6 => 
  array (
    'NodeID' => '6',
    'Name' => '首页',
    'ParentID' => '2',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.index',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  32 => 
  array (
    'NodeID' => '32',
    'Name' => '滚屏图片',
    'ParentID' => '6',
    'TableID' => '7',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.index.slideimg',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  33 => 
  array (
    'NodeID' => '33',
    'Name' => '热门游戏',
    'ParentID' => '6',
    'TableID' => '7',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.index.hotgame',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  34 => 
  array (
    'NodeID' => '34',
    'Name' => '关于我们',
    'ParentID' => '6',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.index.aboutus',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  7 => 
  array (
    'NodeID' => '7',
    'Name' => '游戏中心',
    'ParentID' => '2',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.gamecenter',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  35 => 
  array (
    'NodeID' => '35',
    'Name' => '全部游戏',
    'ParentID' => '7',
    'TableID' => '7',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.gamecenter.allgame',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  36 => 
  array (
    'NodeID' => '36',
    'Name' => '横幅广告',
    'ParentID' => '7',
    'TableID' => '7',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.games.banner',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  8 => 
  array (
    'NodeID' => '8',
    'Name' => '新闻中心',
    'ParentID' => '2',
    'TableID' => '1',
    'PublishMode' => '0',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.newscenter',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  11 => 
  array (
    'NodeID' => '11',
    'Name' => '新闻公告',
    'ParentID' => '8',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.newscenter.xwgg',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  12 => 
  array (
    'NodeID' => '12',
    'Name' => '推荐活动',
    'ParentID' => '8',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.newscenter.tjhd',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  13 => 
  array (
    'NodeID' => '13',
    'Name' => '维护公告',
    'ParentID' => '8',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.newscenter.whgg',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  9 => 
  array (
    'NodeID' => '9',
    'Name' => '客服中心',
    'ParentID' => '2',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.help',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  14 => 
  array (
    'NodeID' => '14',
    'Name' => '常见问题',
    'ParentID' => '9',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.help.common',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  15 => 
  array (
    'NodeID' => '15',
    'Name' => '游戏问题',
    'ParentID' => '9',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.help.game',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  16 => 
  array (
    'NodeID' => '16',
    'Name' => '充值问题',
    'ParentID' => '9',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.help.pay',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  10 => 
  array (
    'NodeID' => '10',
    'Name' => '文档中心',
    'ParentID' => '2',
    'TableID' => '1',
    'PublishMode' => '0',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.doc',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  17 => 
  array (
    'NodeID' => '17',
    'Name' => '关于我们',
    'ParentID' => '10',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.doc.aboutus',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  18 => 
  array (
    'NodeID' => '18',
    'Name' => '联系我们',
    'ParentID' => '10',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.doc.contactus',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  19 => 
  array (
    'NodeID' => '19',
    'Name' => '商务合作',
    'ParentID' => '10',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.doc.cooperation',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  20 => 
  array (
    'NodeID' => '20',
    'Name' => '注册协议',
    'ParentID' => '10',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.www.doc.agreement',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  41 => 
  array (
    'NodeID' => '41',
    'Name' => '法律信息',
    'ParentID' => '10',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => 'law',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  3 => 
  array (
    'NodeID' => '3',
    'Name' => '91yxq游戏官网',
    'ParentID' => '1',
    'TableID' => '1',
    'PublishMode' => '0',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.gameweb',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  70 => 
  array (
    'NodeID' => '70',
    'Name' => '醉武侠',
    'ParentID' => '3',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.zwx',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  71 => 
  array (
    'NodeID' => '71',
    'Name' => '开服列表',
    'ParentID' => '70',
    'TableID' => '6',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.zwx.server',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  72 => 
  array (
    'NodeID' => '72',
    'Name' => '新闻中心',
    'ParentID' => '70',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.zwx.xwzx',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  73 => 
  array (
    'NodeID' => '73',
    'Name' => '新闻',
    'ParentID' => '72',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.zwx.news',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  74 => 
  array (
    'NodeID' => '74',
    'Name' => '公告',
    'ParentID' => '72',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.zwx.notice',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  75 => 
  array (
    'NodeID' => '75',
    'Name' => '活动',
    'ParentID' => '72',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.zwx.activity',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  76 => 
  array (
    'NodeID' => '76',
    'Name' => '滚屏公告',
    'ParentID' => '70',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.zwx.ad',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  77 => 
  array (
    'NodeID' => '77',
    'Name' => '游戏资料',
    'ParentID' => '70',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.zwx.yxzl',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  78 => 
  array (
    'NodeID' => '78',
    'Name' => '新手指南',
    'ParentID' => '77',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.zwx.xszn',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  79 => 
  array (
    'NodeID' => '79',
    'Name' => '高手进阶',
    'ParentID' => '77',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.zwx.gsjj',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  80 => 
  array (
    'NodeID' => '80',
    'Name' => '游戏系统',
    'ParentID' => '77',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.zwx.yxxt',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  81 => 
  array (
    'NodeID' => '81',
    'Name' => '特色玩法',
    'ParentID' => '77',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.zwx.tswf',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  82 => 
  array (
    'NodeID' => '82',
    'Name' => '新手卡',
    'ParentID' => '70',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.zwx.xsk',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  83 => 
  array (
    'NodeID' => '83',
    'Name' => '游戏截图',
    'ParentID' => '70',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.zwx.yxjt',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  84 => 
  array (
    'NodeID' => '84',
    'Name' => '游戏攻略',
    'ParentID' => '70',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.zwx.yxgl',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  55 => 
  array (
    'NodeID' => '55',
    'Name' => '黑暗之光',
    'ParentID' => '3',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hazg',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  69 => 
  array (
    'NodeID' => '69',
    'Name' => '游戏攻略',
    'ParentID' => '55',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hazg.yxgl',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  56 => 
  array (
    'NodeID' => '56',
    'Name' => '开服列表',
    'ParentID' => '55',
    'TableID' => '6',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hazg.server',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  57 => 
  array (
    'NodeID' => '57',
    'Name' => '新闻中心',
    'ParentID' => '55',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hazg.xwzx',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  58 => 
  array (
    'NodeID' => '58',
    'Name' => '新闻',
    'ParentID' => '57',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hazg.news',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  59 => 
  array (
    'NodeID' => '59',
    'Name' => '公告',
    'ParentID' => '57',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hazg.notice',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  60 => 
  array (
    'NodeID' => '60',
    'Name' => '活动',
    'ParentID' => '57',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hazg.activity',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  61 => 
  array (
    'NodeID' => '61',
    'Name' => '滚屏公告',
    'ParentID' => '55',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hazg.ad',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  62 => 
  array (
    'NodeID' => '62',
    'Name' => '游戏资料',
    'ParentID' => '55',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hazg.yxzl',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  63 => 
  array (
    'NodeID' => '63',
    'Name' => '新手指南',
    'ParentID' => '62',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hazg.xszn',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  64 => 
  array (
    'NodeID' => '64',
    'Name' => '高手进阶',
    'ParentID' => '62',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hazg.gsjj',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  65 => 
  array (
    'NodeID' => '65',
    'Name' => '游戏系统',
    'ParentID' => '62',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hazg.yxxt',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  66 => 
  array (
    'NodeID' => '66',
    'Name' => '特色玩法',
    'ParentID' => '62',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hazg.tswf',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  67 => 
  array (
    'NodeID' => '67',
    'Name' => '新手卡',
    'ParentID' => '55',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hazg.xsk',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  68 => 
  array (
    'NodeID' => '68',
    'Name' => '游戏截图',
    'ParentID' => '55',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hazg.yxjt',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  89 => 
  array (
    'NodeID' => '89',
    'Name' => '火焰神',
    'ParentID' => '3',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hys',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  90 => 
  array (
    'NodeID' => '90',
    'Name' => '开服列表',
    'ParentID' => '89',
    'TableID' => '6',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hys.server',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  91 => 
  array (
    'NodeID' => '91',
    'Name' => '新闻中心',
    'ParentID' => '89',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hys.xwzx',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  92 => 
  array (
    'NodeID' => '92',
    'Name' => '新闻',
    'ParentID' => '91',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hys.news',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  93 => 
  array (
    'NodeID' => '93',
    'Name' => '公告',
    'ParentID' => '91',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hys.notice',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  94 => 
  array (
    'NodeID' => '94',
    'Name' => '活动',
    'ParentID' => '91',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hys.activity',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  95 => 
  array (
    'NodeID' => '95',
    'Name' => '滚屏公告',
    'ParentID' => '89',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hys.ad',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  96 => 
  array (
    'NodeID' => '96',
    'Name' => '游戏资料',
    'ParentID' => '89',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hys.yxzl',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  97 => 
  array (
    'NodeID' => '97',
    'Name' => '新手指南',
    'ParentID' => '96',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hys.xszn',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  98 => 
  array (
    'NodeID' => '98',
    'Name' => '高手进阶',
    'ParentID' => '96',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hys.gsjj',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  99 => 
  array (
    'NodeID' => '99',
    'Name' => '游戏系统',
    'ParentID' => '96',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hys.yxxt',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  100 => 
  array (
    'NodeID' => '100',
    'Name' => '特色玩法',
    'ParentID' => '96',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 4,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hys.tswf',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  101 => 
  array (
    'NodeID' => '101',
    'Name' => '新手卡',
    'ParentID' => '89',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hys.xsk',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  102 => 
  array (
    'NodeID' => '102',
    'Name' => '游戏截图',
    'ParentID' => '89',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.msb.yxjt',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  103 => 
  array (
    'NodeID' => '103',
    'Name' => '游戏攻略',
    'ParentID' => '89',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 3,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => '91yxq.hys.yxgl',
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
);
?>